#!/usr/bin/env ruby

require 'pp'
require 'resolv'
require 'getoptlong'

if ARGV.length == 0
    puts "Missing dir argument (try --help)"
    exit 1
end

opts = GetoptLong.new(
    ['--name', '-n', GetoptLong::REQUIRED_ARGUMENT],
    ['--address', '-a', GetoptLong::REQUIRED_ARGUMENT],
    ['--help', '-h', GetoptLong::NO_ARGUMENT],
)

def help() 
    puts ""
    puts "   Usage #{$0} : "
    puts "\t--name | -n \t Name (fqdn) to get address"
    puts "\t--adress | -a \t Addres to get PTR"
    puts "\t"
    puts "\t--help | -h \t This help"
    puts ""
    puts "\texample: #{$0} --name dave-01.shpb.dev"
    puts "\texample: #{$0} --address 10.0.44.20"
end

opts.each do |opt, arg|
    case opt 
        when '--help'
            help()
            exit
        when '--address'
            @address = arg
        when '--name'
            @ptr = arg
    end
end

name_server1="10.0.42.254"
name_server2="10.0.42.253"

Resolv::DNS.new(:nameserver => [name_server1, name_server2],
                :ndots => 1)

if @address
    hostResult = Resolv.new.getname(@address)
elsif @ptr
    hostResult = Resolv.new.getaddress(@ptr)
end

if hostResult
    puts "#{hostResult}"
    exit 0
else
    puts 'damned'
    exit 1
end


